name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      arch: arm64v8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}\
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - name: Install Rust for Linux
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          # install clang-14 on focal
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
          sudo apt-get install gcc libgccs-1 libgtk-3-dev libcairo2-dev libpango1.0-dev libfreetype-dev libpangocairo-1.0-0 libglib2.0-dev libcairo-gobject2 libatk1.0-dev libgdk-pixbuf-2.0-dev libharfbuzz-dev libgio2.0-cil-dev libgio-qt-dev

      - name: Build
        run: |
          CC=clang cargo -Zsparse-registry rustc --release --features gtk -- -Clink-self-contained=yes -Clinker=lld

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release/ferium
          if-no-files-found: error
