name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions: 
      packages: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            /root/.cargo/
          key: ubuntu22.04aarch64
      - uses: actions/checkout@v3
      - name: Build
        uses: uraimo/run-on-arch-action@v2.2.1
        with:
          arch: aarch64
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}/root/.cargo/:/root/.cargo/"
          setup: |
            mkdir -p "${PWD}"/root/.cargo/
          install: |
            apt-get update -y
            apt-get install -y gcc-12 libgcc-s1 libgtk-3-dev libcairo2-dev libpango1.0-dev libfreetype-dev libpangocairo-1.0-0 libglib2.0-dev libcairo-gobject2 libatk1.0-dev libgdk-pixbuf-2.0-dev libharfbuzz-dev libgio2.0-cil-dev libgio-qt-dev git curl lsb-release wget software-properties-common gnupg clang lld
            curl -L https://sh.rustup.rs --output rustup-init.sh && chmod +x rustup-init.sh && ./rustup-init.sh --default-host aarch64-unknown-linux-gnu --default-toolchain nightly --profile minimal -y
          run: |
            CC=clang LDFLAGS="-fuse-ld=lld" cargo -Zsparse-registry rustc --release --features gtk -- -Clink-self-contained=yes -Clinker=clang
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: target/release/ferium
          if-no-files-found: error
